name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for tp? Describe it below.

  - type: textarea
    id: describe-the-feature
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: If you have a specific approach in mind, describe it here.
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about or tried.
    validations:
      required: false
